table d_Calendario
	lineageTag: 8cf0b283-948f-4073-a30d-9d0b3080315f

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 967a9a38-48fe-48a4-a7f1-25ad5e5bf86a
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 3da4b47e-7a46-4931-b73b-9eedc62fb06e
			defaultHierarchy: LocalDateTable_64f323cf-49ab-4c90-abdf-0530f2a363e1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 9310f8d1-9e0b-4cb2-923f-e78722d810de
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = User

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 4e8f71cb-2c33-4a6a-8231-0045a915535b
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = User

	column Mes_Nome
		dataType: string
		lineageTag: 4e4cc946-a1b4-4924-8f63-d14c73a0360a
		summarizeBy: none
		sourceColumn: Mes_Nome
		sortByColumn: Mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Mes_Abreviado
		dataType: string
		lineageTag: 4dc3d548-4abf-4c16-a845-18cfe556be68
		summarizeBy: none
		sourceColumn: Mes_Abreviado
		sortByColumn: Mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AnoMes
		dataType: string
		lineageTag: e12e05dc-958e-439f-99da-f9df241a5bed
		summarizeBy: none
		sourceColumn: AnoMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 23516350-c43b-41eb-b906-a97cd754fb63
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 9be83b6c-d5ce-4e60-92f0-111062452a9b
		summarizeBy: none
		sourceColumn: Dia

		annotation SummarizationSetBy = User

	column Dia_Semana
		dataType: int64
		formatString: 0
		lineageTag: 5c656eee-0a0b-41ce-8044-45898e936923
		summarizeBy: none
		sourceColumn: Dia_Semana

		annotation SummarizationSetBy = User

	column Dia_Semana_Nome
		dataType: string
		lineageTag: adc45e57-44b1-456a-aa5d-808beb78638c
		summarizeBy: none
		sourceColumn: Dia_Semana_Nome

		annotation SummarizationSetBy = Automatic

	column Semana_Ano
		dataType: int64
		formatString: 0
		lineageTag: 8219681a-481e-4930-872c-138e83987d04
		summarizeBy: none
		sourceColumn: Semana_Ano

		annotation SummarizationSetBy = User

	partition d_Calendario = m
		mode: import
		queryGroup: Dimensão
		source =
				let
				    // Fonte da tabela fato
				    Fonte = f_Vendas,
				
				    // Garantia de tipo correto
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte, {{"Data", type date}}),
				
				    // Datas mínima e máxima da fato
				    DataInicial = List.Min(#"Tipo Alterado"[Data]),
				    DataFinal   = List.Max(#"Tipo Alterado"[Data]),
				
				    // Geração da lista de datas
				    ListaDatas = List.Dates(
				        DataInicial,
				        Duration.Days(DataFinal - DataInicial) + 1,
				        #duration(1,0,0,0)
				    ),
				
				    // Criação da tabela calendário
				    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				
				    #"Tipo Alterado Calendario" = Table.TransformColumnTypes(TabelaDatas, {{"Data", type date}}),
				
				    // Colunas de calendário
				    #"Ano" = Table.AddColumn(#"Tipo Alterado Calendario", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mes" = Table.AddColumn(#"Ano", "Mes", each Date.Month([Data]), Int64.Type),
				    #"Mes Nome" = Table.AddColumn(#"Mes", "Mes_Nome", each Date.MonthName([Data]), type text),
				    #"Mes Abreviado" = Table.AddColumn(
				        #"Mes Nome",
				        "Mes_Abreviado",
				        each Text.Start(Date.MonthName([Data]), 3),
				        type text
				    ),
				    #"AnoMes" = Table.AddColumn(
				        #"Mes Abreviado",
				        "AnoMes",
				        each Text.From(Date.Year([Data])) & "-" & Text.PadStart(Text.From(Date.Month([Data])), 2, "0"),
				        type text
				    ),
				    #"Trimestre" = Table.AddColumn(
				        #"AnoMes",
				        "Trimestre",
				        each "T" & Text.From(Date.QuarterOfYear([Data])),
				        type text
				    ),
				    #"Dia" = Table.AddColumn(#"Trimestre", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Dia Semana" = Table.AddColumn(
				        #"Dia",
				        "Dia_Semana",
				        each Date.DayOfWeek([Data]) + 1,
				        Int64.Type
				    ),
				    #"Dia Semana Nome" = Table.AddColumn(
				        #"Dia Semana",
				        "Dia_Semana_Nome",
				        each Date.DayOfWeekName([Data]),
				        type text
				    ),
				    #"Semana Ano" = Table.AddColumn(
				        #"Dia Semana Nome",
				        "Semana_Ano",
				        each Date.WeekOfYear([Data]),
				        Int64.Type
				    )
				
				in
				    #"Semana Ano"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

