table f_Vendas
	lineageTag: 6593acaa-6bc0-41c6-a94e-c89b33fbde41

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: d7abdcb5-a3aa-4df4-905f-49962b92fd4f
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cliente
		dataType: string
		lineageTag: 56bf2c35-08df-4689-adac-b9955729cf23
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: a892cef7-1837-47a7-8096-c954e6760c45
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: #,0
		lineageTag: e796d97a-18b3-4366-95a9-15451d6646f3
		summarizeBy: none
		sourceColumn: Quantidade

		annotation SummarizationSetBy = User

	column Valor
		dataType: int64
		formatString: #,0.00
		lineageTag: 336a2786-530e-4c2f-90f1-6f1d29e0199a
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = User

	column Desconto
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a32cef51-71a5-4240-8f1f-502c703576e5
		summarizeBy: none
		sourceColumn: Desconto

		annotation SummarizationSetBy = User

	column 'Forma de Pagamento'
		dataType: string
		lineageTag: caa255e6-262d-47dc-a32f-9943f5a4ca0f
		summarizeBy: none
		sourceColumn: Forma de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Nº Vezes'
		dataType: int64
		formatString: #,0
		lineageTag: 8cef5b81-5c34-4557-9a21-1512a65f7fde
		summarizeBy: none
		sourceColumn: Nº Vezes

		annotation SummarizationSetBy = User

	column 'Data Vencimento'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d326579-f4db-4a0b-9603-c3d2caf3cbed
		summarizeBy: none
		sourceColumn: Data Vencimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 4acdaf72-e5e5-4447-9e08-74142add9919
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 3e635d96-c760-4f80-8bf8-3eeb0e3924a6
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	partition f_Vendas = m
		mode: import
		queryGroup: Fato
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\daani\OneDrive\Desktop\Daniel\BIs para portifólio\Vendas\Analise_De_Vendas_PowerBI\dados_Vendas_geral.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}, {"Cliente", type text}, {"Produto", type text}, {"Quantidade", Int64.Type}, {"Valor", Int64.Type}, {"Desconto", Percentage.Type}, {"Forma de Pagamento", type text}, {"Nº Vezes", Int64.Type}, {"Data Vencimento", type date}, {"Status", type text}, {"Vendedor", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

